"""APL reference implementation."""

LATEST_LANGUAGE_VERSION = "0.0.4"
SUPPORTED_LANGUAGE_VERSIONS = {"0.0.1", "0.0.2", "0.0.3", "0.0.4"}
LANGUAGE_VERSION = LATEST_LANGUAGE_VERSION
__version__ = "0.0.4"
