{
  "apl":"0.0.10",
  "module":"v010_extra_limit",
  "capabilities":[],
  "limits":{"steps":2,"output_lines":0,"host_reads":0,"extra":1},
  "entry":"main",
  "functions":[
    {
      "name":"main",
      "params":[],
      "returns":"i64",
      "effects":[],
      "body":[
        {"op":"const","id":"answer","type":"i64","value":42},
        {"op":"return","value":"answer"}
      ]
    }
  ]
}
