{
  "apl":"0.0.11",
  "module":"v011_missing_requires",
  "capabilities":[],
  "limits":{"steps":10,"output_lines":0,"host_reads":0},
  "entry":"main",
  "functions":[
    {
      "name":"main",
      "params":[],
      "returns":"i64",
      "effects":[],
      "ensures":[],
      "body":[
        {"op":"const","id":"answer","type":"i64","value":42},
        {"op":"return","value":"answer"}
      ]
    }
  ]
}
