{
  "apl":"0.0.13",
  "module":"v013_zero_unit_exponent",
  "capabilities":[],
  "limits":{"steps":10,"output_lines":0,"host_reads":0},
  "entry":"main",
  "functions":[
    {
      "name":"main",
      "params":[],
      "returns":"i64",
      "effects":[],
      "requires":[],
      "ensures":[],
      "body":[
        {"op":"const","id":"raw","type":"i64","value":1},
        {"op":"quantity.attach","id":"q","type":{"quantity":{"m":0}},"args":["raw"]},
        {"op":"quantity.value","id":"wide","type":"i64","args":["q"]},
        {"op":"return","value":"wide"}
      ]
    }
  ]
}
